name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - '.github/workflows/**'

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: clippy
      - run: cargo check
      - run: cargo test
      - run: cargo clippy
